### ISSUE TITLE
Cant get TextTracks for DASH media source type

### ISSUE THREAD

**Issue by oahmedazab** [kaltura/playkit-android#556]
I am using KalturaOvpMediaProvider Api to get mediaEntry,

this entry has 3 closed captions added from KMC console. i can see them from console and web embedded player V3 and V2

However when i am querying player on android for available tracks i find textTracks size is 0

I am using playkit and playkitproviders Version :3.9.6
and tried running it on android version 7,8 and 9

Notes:
DRM in enabled for this entry and i notice that the media source type is DASH

Thanks

**Comment by giladna** [comment]
@oahmedazab 

seems like your account was not configured to play dash + CC

waht is your partner id?

**Comment by oahmedazab** [comment]
@giladna 
can i send it to you via email?

thanks

**Comment by giladna** [comment]
@oahmedazab 
 yes

gilad.nadav@kaltura.com

**Comment by oahmedazab** [comment]
@giladna 

sent, thank you
