### ISSUE TITLE
JsonParseException in OvpResultAdapter, Android 9

### ISSUE THREAD

**Issue by oahmedazab** [kaltura/playkit-android#564]
i am seeing the following exception on Android 9

any insights about this issue or how we can avoid it for now

thanks 

`Fatal Exception: com.google.gson.JsonParseException: Adaptor failed to parse result, com.kaltura.playkit.providers.api.ovp.model.KalturaStartWidgetSessionResponse
       at com.kaltura.playkit.providers.api.ovp.model.OvpResultAdapter.deserialize + 64(OvpResultAdapter.java:64)
       at com.kaltura.playkit.providers.api.ovp.model.OvpResultAdapter.deserialize + 39(OvpResultAdapter.java:39)
       at com.google.gson.internal.bind.TreeTypeAdapter.read + 69(TreeTypeAdapter.java:69)
       at com.google.gson.Gson.fromJson + 927(Gson.java:927)
       at com.google.gson.Gson.fromJson + 994(Gson.java:994)
       at com.google.gson.Gson.fromJson + 967(Gson.java:967)
       at com.kaltura.netkit.utils.GsonParser.parse + 26(GsonParser.java:26)
       at com.kaltura.netkit.utils.GsonParser.parseArray + 37(GsonParser.java:37)
       at com.kaltura.playkit.providers.api.ovp.KalturaOvpParser.parse + 56(KalturaOvpParser.java:56)
       at com.kaltura.playkit.providers.api.ovp.KalturaOvpParser.parse + 48(KalturaOvpParser.java:48)
       at com.kaltura.playkit.providers.ovp.KalturaOvpMediaProvider$Loader.onEntryInfoMultiResponse + 292(KalturaOvpMediaProvider.java:292)
       at com.kaltura.playkit.providers.ovp.KalturaOvpMediaProvider$Loader.access$700 + 183(KalturaOvpMediaProvider.java:183)
       at com.kaltura.playkit.providers.ovp.KalturaOvpMediaProvider$Loader$1.onComplete + 245(KalturaOvpMediaProvider.java:245)
       at com.kaltura.playkit.providers.ovp.KalturaOvpMediaProvider$Loader$1.onComplete + 238(KalturaOvpMediaProvider.java:238)
       at com.kaltura.netkit.connect.request.RequestBuilder$1.onComplete + 151(RequestBuilder.java:151)
       at com.kaltura.netkit.connect.executor.APIOkRequestsExecutor$2.onResponse + 191(APIOkRequestsExecutor.java:191)
       at com.google.firebase.perf.network.zzg.onResponse + 22(zzg.java:22)
       at okhttp3.RealCall$AsyncCall.execute + 206(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run + 32(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1167(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run + 764(Thread.java:764)`

**Comment by giladna** [comment]
@oahmedazab 
need more info

is it working ok on lower versions?
what is your SDK version?

could you send charles logs for the multirequest?

**Comment by oahmedazab** [comment]
@giladna 

> is it working ok on lower versions?

i tried it on lower version and i faced the same issue

> what is your SDK version?

i tried it on 3.9.6
and 4.0.0

> could you send charles logs for the multirequest?

i guess it has something to do with proguard
`
java.lang.ClassNotFoundException: com.kaltura.playkit.providers.api.ovp.model.KalturaStartWidgetSessionResponse
                         W      at java.lang.Class.classForName(Native Method)
                         W      at java.lang.Class.forName(Class.java:453)
                         W      at java.lang.Class.forName(Class.java:378)
                         W      at com.kaltura.playkit.providers.api.ovp.model.OvpResultAdapter.a(OvpResultAdapter.java:58)
                         W      at com.kaltura.playkit.providers.api.ovp.model.OvpResultAdapter.a(OvpResultAdapter.java:39)
                         W      at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
                         W      at com.google.gson.q.a(Gson.java:927)
                         W      at com.google.gson.q.a(Gson.java:994)
                         W      at com.google.gson.q.a(Gson.java:967)
                         W      at com.kaltura.netkit.utils.GsonParser.parse(GsonParser.java:26)
                         W      at com.kaltura.netkit.utils.GsonParser.parseArray(GsonParser.java:37)
                         W      at com.kaltura.playkit.c.a.b.b.a(KalturaOvpParser.java:56)
                         W      at com.kaltura.playkit.c.a.b.b.a(KalturaOvpParser.java:48)
                         W      at com.kaltura.playkit.c.c.c$a.a(KalturaOvpMediaProvider.java:292)
                         W      at com.kaltura.playkit.c.c.c$a.a(KalturaOvpMediaProvider.java:183)
                         W      at com.kaltura.playkit.c.c.b.a(KalturaOvpMediaProvider.java:245)
                         W      at com.kaltura.playkit.c.c.b.onComplete(KalturaOvpMediaProvider.java:238)
                         W      at b.c.a.a.b.c.a(RequestBuilder.java:151)
                         W      at b.c.a.a.a.b.a(APIOkRequestsExecutor.java:191)
                         W      at com.google.firebase.perf.network.g.a(Unknown Source:22)
                         W      at d.I$a.b(RealCall.java:206)
                         W      at d.a.b.run(NamedRunnable.java:32)
                         W      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                         W      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                         W      at java.lang.Thread.run(Thread.java:764)
                         W  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.kaltura.playkit.providers.api.ovp.model.KalturaStartWidgetSessionResponse" on path: DexPathList[[zip file "/data/app/com.teletica.tdmas-7EbnPW6W_fAaJkFYdkwF8A==/base.apk"],nati
                            veLibraryDirectories=[/data/app/com.teletica.tdmas-7EbnPW6W_fAaJkFYdkwF8A==/lib/arm64, /system/lib64, /system/vendor/lib64]]
                         W      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                         W      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                         W      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                         W      ... 25 more
         AndroidRuntime  E  FATAL EXCEPTION: OkHttp Dispatcher
                         E  Process: com.teletica.tdmas, PID: 3773
                         E  com.google.gson.JsonParseException: Adaptor failed to parse result, com.kaltura.playkit.providers.api.ovp.model.KalturaStartWidgetSessionResponse
                         E      at com.kaltura.playkit.providers.api.ovp.model.OvpResultAdapter.a(OvpResultAdapter.java:64)
                         E      at com.kaltura.playkit.providers.api.ovp.model.OvpResultAdapter.a(OvpResultAdapter.java:39)
                         E      at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
                         E      at com.google.gson.q.a(Gson.java:927)
                         E      at com.google.gson.q.a(Gson.java:994)
                         E      at com.google.gson.q.a(Gson.java:967)
                         E      at com.kaltura.netkit.utils.GsonParser.parse(GsonParser.java:26)
                         E      at com.kaltura.netkit.utils.GsonParser.parseArray(GsonParser.java:37)
                         E      at com.kaltura.playkit.c.a.b.b.a(KalturaOvpParser.java:56)
                         E      at com.kaltura.playkit.c.a.b.b.a(KalturaOvpParser.java:48)
                         E      at com.kaltura.playkit.c.c.c$a.a(KalturaOvpMediaProvider.java:292)
                         E      at com.kaltura.playkit.c.c.c$a.a(KalturaOvpMediaProvider.java:183)
                         E      at com.kaltura.playkit.c.c.b.a(KalturaOvpMediaProvider.java:245)
                         E      at com.kaltura.playkit.c.c.b.onComplete(KalturaOvpMediaProvider.java:238)
                         E      at b.c.a.a.b.c.a(RequestBuilder.java:151)
                         E      at b.c.a.a.a.b.a(APIOkRequestsExecutor.java:191)
                         E      at com.google.firebase.perf.network.g.a(Unknown Source:22)
                         E      at d.I$a.b(RealCall.java:206)
                         E      at d.a.b.run(NamedRunnable.java:32)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                         E      at java.lang.Thread.run(Thread.java:764)
`

**Comment by giladna** [comment]
@oahmedazab 
without proguard it works fine?

try this

https://kaltura.github.io/playkit/guide/android/core/proguard.html

gilad.

**Comment by oahmedazab** [comment]
@giladna 

thanks alot that solved the problem.

i was getting the proguard rules from this md
https://github.com/kaltura/playkit-android/blob/dev/docs/ProGuard.md

if we can update it for future users

thanks
