### ISSUE TITLE
[Question] Is KavaAnalyticsPlugin and KalturaAnalyticsPlugin the same?

### ISSUE THREAD

**Issue by oahmedazab** [kaltura/playkit-android#579]
Hello there, i was trying to integrate kaltura analytics following this documentation
https://vpaas.kaltura.com/documentation/Mobile-Video-Player-SDKs/v3_Android_Analytics.html#kaltura-analytics-plugin

however i couldn't find KalturaAnalyticsPlugin anywhere, if found another plugin https://github.com/kaltura/playkit-android-kava

is that the correct plugin to use?

thanks

**Comment by giladna** [comment]
hi @oahmedazab 
kaltura-analytics is deprecated and it was removed from SDK
KAVA is the plugin that has to be used. see sample below
[https://github.com/kaltura/playkit-android-samples/blob/develop/FullDemo/playkitdemo/src/main/java/com/kaltura/playkitdemo/MainActivity.java](url)
