### ISSUE TITLE
React Native Integration

### ISSUE THREAD

**Issue by yash-outlier** [kaltura/playkit-android#637]
Please provide documentation to integrate this with react-native.

**Comment by giladna** [comment]
@yash-outlier 

could you look at this repo\let me know if it is helpful did not test it myself

https://github.com/rafalkaczynsky/react-native-kaltura-player-v3

**Comment by yash-outlier** [comment]
@giladna Thanks you for replying, but this npm module is 2+ years old and does not work with the latest version.

**Comment by GouravSna** [comment]
Hi @yash-outlier , We have released react native kaltura player. Feel free to test our Alpha version. It's not production ready yet. 
https://github.com/kaltura/kaltura-player-rn
