### ISSUE TITLE
jcenter is shutting down

### ISSUE THREAD

**Issue by egor-n** [kaltura/playkit-android#692]
##### Prerequisites
- [x] Have you checked for duplicate [issues](https://github.com/kaltura/playkit-android/issues)

[jcenter is shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) and playkit-android is currently hosted there. It will become read-only on **March 31st, 2021** and will be terminated on **February 1st, 2022**. Please consider switching from jcenter to [Maven Central](https://central.sonatype.org/pages/producers.html).

**Comment by giladna** [comment]
v4.13.3 and on are maven central artifacts
