### ISSUE TITLE
Ad events (AD_LOAD_TIMEOUT_TIMER_STARTED and ERROR) are not fired 

### ISSUE THREAD

**Issue by YHossam** [kaltura/playkit-android#719]
I have integrated IMAConfig to my Kaltura player implementation, but when playing offline content while the internet is not connected, the player keeps loading the Ad and never stops.

The player also didn't fire any of those events: 

AdEvent.Type.AD_LOAD_TIMEOUT_TIMER_STARTED and AdEvent.Type.ERROR

Is there any way, even in feature, to make the player fire those events or any other events to indicate Ad load timeout?

**Comment by giladna** [comment]
@YHossam 

when you play offline please do not add IMA Plugin when you create the player 
we do not support offline ads

**Comment by giladna** [comment]
@YHossam 
When no Network you will get 
2021-06-10 14:34:21.971 28315-28315/com.kaltura.playkitdemo E/IMAPlugin: Event: onAdErrorAdErrorCode [name: FAILED_TO_REQUEST_ADS, number: 1005]

Ad Event ERROR errorType = FAILED_TO_REQUEST_ADS errorMessage = There was a problem requesting ads from the server.
```
 player.addListener(this, AdEvent.error, event -> {
            if (event != null && event.error != null) {
                String cause = (event.error.exception != null && event.error.exception.getCause() != null) ? event.error.exception.getCause().getMessage() : "";
                log.d("Ad Event ERROR errorType = " + event.error.errorType + " errorMessage = " + event.error.message + " cause = " + cause);
            }
        });
```
so you can register to this event and be informed

**Comment by YHossam** [comment]
Hello @giladna, Thanks for your response, 

I have identified the issue, it's related to IMAConfig Initialization 

when I initialize IMAConfig without enabling debug mode with this line 

` IMAConfig().setAdTagUrl(content.adUrl)`

The library doesn't deliver AdEvent.error and I couldn't identify if the ad was errored or not

but when i init IMAConfig with enabling debug mode 

`IMAConfig().setAdTagUrl(content.adUrl).enableDebugMode(true)`

the library delivers the event AdEvent.error and could identify if the ad was errored.

**Comment by GouravSna** [comment]
Hi @YHossam ,

I don't see such issue. 
Please let us know which playkit version you are using and can you try to reproduce this on our standalone IMA [sample](https://github.com/kaltura/playkit-android-samples/tree/develop/IMASample). In case, if you can see the issue, please share a forked branch with user-steps.
