### ISSUE TITLE
Video can not play error occur.

### ISSUE THREAD

**Issue by Office-Murtaza** [kaltura/playkit-android#769]
com.kaltura.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/mp4v-es, null, -1, null, [720, 1280, 14.999536], [-1, -1]), format_supported=YES

Video have above error. But when play same video in gallery player its working fine. This error occure sumsang android 11 A515F. But not occure in google pixel 5 and below 11 samsung versions.

**Comment by GouravSna** [comment]
> Video have above error. But when play same video in gallery player its working fine. 

Please explain this.

> This error occure sumsang android 11 A515F. But not occure in google pixel 5 and below 11 samsung versions.

What is the OS Build version for Google Pixel 5 ?

**Comment by Office-Murtaza** [comment]
> > This error occure sumsang android 11 A515F. But not occure in google pixel 5 and below 11 samsung versions.


>  kulture player not play the video in sumsang android 11 A515F.  the video which is not play by player is the result of  ffmpeg command.But the same video process by ffmpeg plays video kaltura player in google pixel 5. How to solve this problem in sumsang device.   com.kaltura.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/mp4v-es, null, -1, null, [720, 1280, 14.999536], [-1, -1]), format_supported=YES this is the exception which is throws by kulture player. Sorry for bad english.


> What is the OS Build version for Google Pixel 5 ?
   android 11 version

**Comment by GouravSna** [comment]
Please send the media on dev.kaltura@gmail.com

**Comment by Office-Murtaza** [comment]
> Please send the media on [dev.kaltura@gmail.com](mailto:dev.kaltura@gmail.com)

Changing ffmpeg's video encoding does not produce player video playback errors. But using fmpeg video encoding format mpeg4 player produces error in some devices.

**Comment by Office-Murtaza** [comment]
Changing ffmpeg's video codec with x.264 does not produce player playback error. But using fmpeg video codec format mpeg4 player produces error in some sumsung devices above android version 10.
